gitConfig:
  pull.rebase: 'true'

image:
  file: .gitpod.Dockerfile

ports:
  - port: 5433 # PostgreSQL
    onOpen: ignore

  - port: 5672 # RabbitMQ
    onOpen: ignore

  - port: 6380 # Redis
    onOpen: ignore

  - port: 9000 # MinIO
    onOpen: ignore

  - port: 9001 # MinIO Dashboard
    onOpen: ignore

  - port: 15672 # RabbitMQ Dashboard
    onOpen: ignore

  - port: 30000 # Testcase Server
    onOpen: ignore

tasks:
  - name: Setup
    before: docker compose up -d
    init: ./scripts/setup.sh

github:
  prebuilds:
    addBadge: true

vscode:
  extensions:
    - 42crunch.vscode-openapi
    - bradlc.vscode-tailwindcss
    - csstools.postcss
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
    - golang.go
    - hashicorp.terraform
    - humao.rest-client
    - johnsoncodehk.vscode-typescript-vue-plugin
    - ms-azuretools.vscode-docker
    - prisma.prisma
    - rangav.vscode-thunder-client
    - redhat.vscode-yaml # dependency of openapi
    - Vue.volar
