version: '3'
services:
  app:
    profiles: ['devcontainer']
    container_name: skkuding-dev
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:16-bullseye
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    environment:
      DEVCONTAINER: 1
  dev-db:
    container_name: skkuding-dev-db
    image: postgres:14-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: skkuding
  test-db:
    profiles: ['test']
    container_name: skkuding-test-db
    image: postgres:14-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: skkuding
  dev-cache:
    container_name: skkuding-dev-cache
    image: redis:7-alpine
    ports:
      - 6380:6379
  dev-mq:
    image: rabbitmq:3-management-alpine
    container_name: skkuding-dev-mq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: RabbitMQ-My-Cookies
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: 1234
