openapi: 3.1.0
info:
  version: 0.1.0
  title: Codedang Client API
  summary: REST API for Codedang Client
  description: |
    ## 🎈 Overview
    Codedang is an online judge for students to practice their coding skills.  
    Codedang client API can be used by general users.
servers:
  - url: http://localhost:4000
    description: Local server
paths:
  /auth/login:
    post:
      summary: Login
      description: Login to Codedang
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: admin
                password:
                  type: string
                  example: Adminadmin
